version: '3'
services:
  nginx:
    image: nginx:1.18
    ports:
      - "80:80"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  db:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'r00t'
      MYSQL_DATABASE: 'modx'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  php:
      build: ./images/php
      volumes:
        - ./www:/var/www
      links: 
        - db

